import { Router } from "express";
import { upload } from "../lib/multer.js";
import { allArtists, artistDetails, artistLogin, availableTickets, concertDetails, createConcert, currentLoggedUser, delManyConcerts, gatherAllConcertDetails, ticketBooking, ticketPayment, updateConcerts, userLogin, userSignUp } from "../controllers/index.js";
import { verify } from "../lib/middleware.js";
const router = Router();
router.route("/user/signup").post(userSignUp);
router.route("/user").post(userLogin);
router.route("/artist").post(upload.single("image"),artistLogin);
router.route("/ticket/buy/:concertId").post(verify,ticketBooking);
router.route("/ticket/available/:concertId").get(verify,availableTickets);
router.route("/concert/:concertId").get(verify,concertDetails);
router.route("/concerts").get(verify,gatherAllConcertDetails);
router.route("/concert/:artistId").post( upload.single("poster"),createConcert);
router.route("/artists").get(allArtists);
router.route("/artist/:id").get(artistDetails);
router.route("/user/current").get(verify , currentLoggedUser);
router.route("/ticket/payment/:reservationId").post(verify , ticketPayment);
router.route("/delete/concerts").delete(delManyConcerts);
router.route("/update/concerts").put(updateConcerts);
export {router};